pipeline {

    agent {
        docker {
            image 'docker:20.10-dind'
            args '--privileged'
        }
    }

    stages {

        stage('Testes Unitários') {
            echo 'Rodando testes unitários'
        }
        stage('Testes de Integração') {
            echo 'Rodando testes de integração'
        }
        stage('SAST Trivy') {
            echo 'Rodando SAST'
        }
        // Build da Imagem Docker
        stage('Build Backend Image') { 
             // Steps
            steps {
               sh 'docker build -t paulofabiano/lista-tarefas:v1 -f Dockerfile.Spring' 
            }
        }

    }

}