pipeline {

    agent {
        docker {
            image 'alpine:3.23.0'
        }
    }

    stages {
        stage('Config Alpine') {
            steps {
                echo 'Instalando CURL'
                sh 'apk add curl'
                
                echo 'Instalando DockerCLI'
                sh 'apk add docker-cli'
            }
        }
        stage('Install Trivy') {
            steps {
                echo 'Instalando Trivy'
                sh 'curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.68.1'
            }
        }
        stage('Scan Projeto') {
            steps {
                sh 'trivy fs --scanners vuln,secret,misconfig .'
            }
        }
        stage('Testes Unitários') {
            steps {
                echo 'Rodando testes unitários'
            }
        }
        stage('Testes de Integração') {
            steps {
                echo 'Rodando testes de integração'
            }
        }
        stage('Build Backend Image') { 
             // Steps
            steps {
               sh 'docker build -t paulofabiano/lista-tarefas:v1 -f Dockerfile.Spring .' 
            }
        }
        stage('Scan Backend Image') {
            steps {
                sh 'trivy image paulofabiano/lista-tarefas:v1'
            }
        }

    }

}