pipeline {

    agent {
        docker {
            image 'openjdk:27-ea-slim'
        }
    }

    stages {
        // Build da Imagem Docker
        stage('Build Backend') { 
             // Steps
            steps {
               sh 'mvn clean install -DskipTests -Dmaven.test.skip=true -Dmaven.build.dest=/app/target' 
            }
        }

    }

}